const fs = require('fs')

let read = (filename) => {
    return fs.readFileSync(filename, 'utf-8')
}

exports.cogs = read('./queries/cogs_normal.sql')
exports.cogsbackup = read('./queries/cogs_backup.sql')
exports.cogsreport = read('./queries/cogs_report.sql')
exports.cogsSuper = read('./queries/cogs_super.sql')
exports.revenue = read('./queries/revenue_normal.sql')
exports.revenuebackup = read('./queries/revenue_backup.sql')
exports.revenuereport = read('./queries/revenue_report.sql')
exports.revenueSuper = read('./queries/revenue_super.sql')
exports.vobbackup = read('./queries/vob_backup.sql')
exports.vob = read('./queries/vob_normal.sql')
exports.vobreport = read('./queries/vob_report.sql')
exports.vobSuper = read('./queries/vob_super.sql')
exports.surgCount = read('./queries/surgery_count.sql')
exports.cogsCount = read('./queries/cogs_count.sql')
exports.breakup = read('./queries/breakup_normal.sql')
exports.breakupSuper = read('./queries/breakup_super.sql')
exports.breakupmtd = read('./queries/breakup_mtd_normal.sql')
exports.breakupmtdSuper = read('./queries/breakup_mtd_super.sql')
exports.breakupReport = read('./queries/breakup_backup.sql')
exports.nativebreakup = read('./queries/breakup_normal_revenue.sql')
exports.nativebreakupSuper = read('./queries/breakup_super_revenue.sql')
exports.nativebreakupmtd = read('./queries/breakup_mtd_normal_revenue.sql')
exports.nativebreakupmtdSuper = read('./queries/breakup_mtd_super_revenue.sql')
exports.nativebreakupReport = read('./queries/breakup_backup_revenue.sql')
exports.nativerevenue = read('./queries/revenue_normal_revenue.sql')
exports.nativerevenuebackup = read('./queries/revenue_backup_revenue.sql')
exports.nativerevenuereport = read('./queries/revenue_report_revenue.sql')
exports.nativerevenueSuper = read('./queries/revenue_super_revenue.sql')