SELECT ORGCRE.DESCRIPTION AS entity,A.*  FROM
(
SELECT 
	-- ROC.DESCRIPTION AS 'entity',
	DATE(PATIENTBILL.REVENUE_DATE) AS 'TRANSACTION_DATE',
 	ACCUNIT.`ACCOUNTUNIT` AS 'BILLED', 
 	CASE WHEN SUBSTRING(PATIENT.`PATIENTID`,1,3) IN ('GPP','CTP','MLK','NLP','NMB','VRH') THEN ACCUNIT.`ACCOUNTUNIT`
	ELSE
	IFNULL(SUBSTRING(PATIENT.`PATIENTID`,1,3),ACCUNIT.`ACCOUNTUNIT`)
	END AS 'NATIVE',
	IF(PAYORTYPE.PAYORCATEGORY IS NULL, 'Self', IF(PAYORTYPE.PAYORCATEGORY ='Cash','Self',PAYORTYPE.PAYORCATEGORY)) AS PAYORTYPE,
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.CUSTOMERNAME,PATIENT.PATIENTNAME) AS PAYER_NAME,
	IF(PAYORTYPE.PAYORCATEGORY IS NULL, 'SELF PAYING', PAYORTYPE.PAYORTYP) AS AGENCY_NAME,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),IF(CAT.`ITMCGCATEGNAME`='LENS','OPTICALS',SUBSTRING(DEPT.DEPARTMENTNAME,5,LENGTH(DEPT.DEPARTMENTNAME))),ACCHEAD.ACCOUNTHEAD) AS UNIT,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),CAT.`ITMCGCATEGNAME`,SUB.`ACCOUNTSUBHEAD`) AS 'GROUP',
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),ITEM.SUBCATEGORY,LED.`LEDGER`) AS 'SUBGROUP',
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.CUSTOMERNO,PATIENT.PATIENTID) AS MRN,
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.CUSTOMERNAME,PATIENT.PATIENTNAME) AS PATIENT_NAME,
	IF(RDRT.REFERRALTYPENAME IS NULL, '', RDRT.REFERRALTYPENAME) AS REFERRAL_TYPE,
	IF(RDRB.REFERREDBYNAME IS NULL, '', RDRB.REFERREDBYNAME) AS REFERRAL_BY,
	PATIENT.REFERRALTYPEHIDDEN AS REFERRAL_VALUE,
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.AGE,PATIENT.AGE) AS PATIENT_AGE,
	DATE(RIC.CREATEDTIME) AS REGISTERED_DATE,
	IF(PATIENTBILL.PATIENT_ID IS NULL, 'DIRECT SALES', IF(DATEDIFF(DATE(PATIENTBILL.REVENUE_DATE),DATE(RIC.CREATEDTIME)) = 0, 'NEW', 'REVIEW')) AS VISIT_TYPE,
	IF(PATIENTBILL.PATIENT_ID IS NULL, 0, DATEDIFF(DATE(PATIENTBILL.REVENUE_DATE),DATE(RIC.CREATEDTIME))) AS VISIT_DAYS,
	PATIENTBILL.BILL_NO AS BILLNO,
	PATIENTBILL.ID AS EXTERNAL_ID,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%') ,ITEM.ITEMCODE,CHARGE.CHARGECODE) AS ITEMCODE,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%') ,SALDETAIL.ITEMNAME,CHARGE.CHARGE) AS ITEMNAME,
	ITEM.MANUFACTURERID AS MANUFACTURER,
	IF( SERVICE.SERVICE_ID LIKE ('DSAL%'),SALDETAIL.QUANTITY,SERVICE.QUANTITY) AS QUANTITY,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),(SALDETAIL.QUANTITY*SALDETAIL.MRP) ,SERVICE.SERVICE_AMOUNT) AS TOTAL_AMOUNT,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),SALDETAIL.DISCOUNTAMOUNT,SERVICE.SERVICE_DISCOUNT) AS DISCOUNT_AMOUNT,	
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),((SALDETAIL.QUANTITY*SALDETAIL.MRP)-IF(SALDETAIL.DISCOUNTAMOUNT IS NULL,0,SALDETAIL.DISCOUNTAMOUNT)) ,(SERVICE.SERVICE_AMOUNT - SERVICE.SERVICE_DISCOUNT)) AS NET_AMOUNT,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),((SALDETAIL.QUANTITY*SALDETAIL.MRP)-IF(SALDETAIL.DISCOUNTAMOUNT IS NULL,0,SALDETAIL.DISCOUNTAMOUNT)) ,(SERVICE.SERVICE_AMOUNT - SERVICE.SERVICE_DISCOUNT-SERVICE.CLAIM_AMOUNT)) AS PATIENT_AMOUNT,
	SERVICE.CLAIM_AMOUNT AS PAYOR_AMOUNT,
		IFNULL(TAX.VALUE,0) AS CGST,
	IFNULL(TAX1.VALUE,0) AS SGST,
	IFNULL(TAX.VALUE+TAX1.VALUE,0) AS 'GST%',
	IF(TAX.VALUE+TAX1.VALUE IS NULL , IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),((SALDETAIL.QUANTITY*SALDETAIL.MRP)-IF(SALDETAIL.DISCOUNTAMOUNT IS NULL,0,SALDETAIL.DISCOUNTAMOUNT)) ,(SERVICE.SERVICE_AMOUNT - SERVICE.SERVICE_DISCOUNT)),
	IF(SERVICE.SERVICE_ID LIKE ('DSAL%'),ROUND(100/(100+(TAX.VALUE+TAX1.VALUE))*((SALDETAIL.TOTAL - IF(SALDETAIL.DISCOUNTAMOUNT IS NULL, 0, SALDETAIL.DISCOUNTAMOUNT))),2),0) )AS 'Net_Amount_W/O_GST',
	IF(SERVICE.SERVICE_ID LIKE ('DSAL%'),ROUND((100/(100+(TAX.VALUE+TAX1.VALUE))*((SALDETAIL.TOTAL - IF(SALDETAIL.DISCOUNTAMOUNT IS NULL, 0, SALDETAIL.DISCOUNTAMOUNT)) * (TAX.VALUE/100))),2),0) AS 'CGST_Value',
	IF(SERVICE.SERVICE_ID LIKE ('DSAL%'),ROUND((100/(100+(TAX.VALUE+TAX1.VALUE))*((SALDETAIL.TOTAL - IF(SALDETAIL.DISCOUNTAMOUNT IS NULL, 0, SALDETAIL.DISCOUNTAMOUNT)) * (TAX1.VALUE/100))),2),0) AS 'SGST_Value'
FROM
	BILL_CREDIT_DEBIT_AUDIT AS CREDITDEBIT
	INNER JOIN BILL_PATIENT_BILL AS PATIENTBILL ON PATIENTBILL.ID = CREDITDEBIT.BILL_ID
	INNER JOIN `RT_DATA_ACCOUNT_UNIT` AS ACCUNIT ON ACCUNIT.ID = CREDITDEBIT.`ACCOUNT_UNIT`
	INNER JOIN BILL_SERVICE_DETAIL AS SERVICE ON SERVICE.ID = CREDITDEBIT.BILL_DETAIL_ID
	LEFT JOIN RT_TICKET_DIRECTSALESDETAIL SALDETAIL ON SALDETAIL.SALESID = SERVICE.SERVICE_ID
	LEFT JOIN RT_DATA_CHARGE_DETAIL AS CHARGEDETAIL ON CHARGEDETAIL.ID = SERVICE.CHARGEDETAIL_ID
	INNER JOIN RT_DATA_CORE AS CORE ON CORE.ID = CHARGEDETAIL.ID
	-- JOIN RT_ORGANIZATION_CORE ROC ON ROC.ID=CORE.TENANTID
	INNER JOIN RT_DATA_CHARGE AS CHARGE ON CHARGE.ID = CORE.PARENT_TICKET_ID
	INNER JOIN RT_DATA_ACCOUNT_HEAD AS ACCHEAD ON ACCHEAD.ID = CHARGE.CHARGACCOUNTHEAD
	INNER JOIN `RT_DATA_ACCOUNTSUBHEAD` SUB ON SUB.ID=CHARGE.ACCSUBHEAD
	INNER JOIN `RT_DATA_LEDGER` LED ON LED.ID=CHARGE.CHARGELEDGER
	LEFT JOIN RT_INDIVIDUAL_PATIENT AS PATIENT ON PATIENTBILL.`PATIENT_ID`= PATIENT.ID
	LEFT JOIN RT_INDIVIDUAL_CORE AS RIC ON RIC.ID=PATIENT.ID
	LEFT JOIN RT_DATA_REFERRAL_TYPE RDRT ON RDRT.ID=PATIENT.REFERRALTYPE
	LEFT JOIN RT_DATA_REFERRED_BY RDRB ON RDRB.ID=PATIENT.REFERREDBYCONSULTANT
	LEFT JOIN RT_INDIVIDUAL_CUSTOMER AS CUSTOMER ON CUSTOMER.ID = PATIENTBILL.CUSTOMER_ID
	LEFT JOIN RT_DATA_PAYORTYPE AS PAYORTYPE ON PATIENTBILL.PAYOR_TYPE_ID = PAYORTYPE.ID
	LEFT JOIN RT_DATA_ITEM ITEM ON ITEM.ID = SALDETAIL.ITEMID
	LEFT JOIN RT_DATA_TAX AS TAX ON ITEM.CGST = TAX.ID
	LEFT JOIN RT_DATA_TAX AS TAX1 ON ITEM.SGST = TAX1.ID	
	LEFT JOIN RT_DATA_DEPARTMENT DEPT ON DEPT.ID = SALDETAIL.DEPTID
	LEFT JOIN `RT_DATA_ITEM_CATEGORY` CAT ON CAT.ID = ITEM.CATEGORY
WHERE
	DATE(PATIENTBILL.REVENUE_DATE) BETWEEN curdate() AND curdate()
   	 AND CREDITDEBIT.AMOUNT > 0 
   	-- AND IF(SUBSTRING(PATIENT.`PATIENTID`,1,3) IN('GPP','CTP','MLK','NLP','NMB','VRH') ,ACCUNIT.`ACCOUNTUNIT`, IFNULL(SUBSTRING(PATIENT.`PATIENTID`,1,3),ACCUNIT.`ACCOUNTUNIT`)) = 'CMH'
UNION ALL	
SELECT
	-- ROC.DESCRIPTION AS 'entity',
	DATE(CREDITDEBIT.CREATED_TIME) AS 'TRANSACTION_DATE',
 	ACCUNIT.`ACCOUNTUNIT` AS 'BILLED', 
 	CASE WHEN SUBSTRING(PATIENT.`PATIENTID`,1,3) IN ('GPP','CTP','MLK','NLP','NMB','VRH') THEN ACCUNIT.`ACCOUNTUNIT`
	ELSE
	IFNULL(SUBSTRING(PATIENT.`PATIENTID`,1,3),ACCUNIT.`ACCOUNTUNIT`)
	END AS 'NATIVE',
	IF(PAYORTYPE.PAYORCATEGORY IS NULL, 'Self', IF(PAYORTYPE.PAYORCATEGORY ='Cash','Self',PAYORTYPE.PAYORCATEGORY)) AS PAYORTYPE,
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.CUSTOMERNAME,PATIENT.PATIENTNAME) AS PAYER_NAME,
	IF(PAYORTYPE.PAYORCATEGORY IS NULL, 'SELF PAYING', PAYORTYPE.PAYORTYP) AS AGENCY_NAME,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),IF(CAT.`ITMCGCATEGNAME`='LENS','OPTICALS',SUBSTRING(DEPT.DEPARTMENTNAME,5,LENGTH(DEPT.DEPARTMENTNAME))),ACCHEAD.ACCOUNTHEAD) AS UNIT,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),CAT.`ITMCGCATEGNAME`,SUB.`ACCOUNTSUBHEAD`) AS 'GROUP',
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),ITEM.SUBCATEGORY,LED.`LEDGER`) AS 'SUBGROUP',
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.CUSTOMERNO,PATIENT.PATIENTID) AS MRN,
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.CUSTOMERNAME,PATIENT.PATIENTNAME) AS PATIENT_NAME,
		IF(RDRT.REFERRALTYPENAME IS NULL, '', RDRT.REFERRALTYPENAME) AS REFERRAL_TYPE,
	IF(RDRB.REFERREDBYNAME IS NULL, '', RDRB.REFERREDBYNAME) AS REFERRAL_BY,
	PATIENT.REFERRALTYPEHIDDEN AS REFERRAL_VALUE,
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.AGE,PATIENT.AGE) AS PATIENT_AGE,
	DATE(RIC.CREATEDTIME) AS REGISTERED_DATE,
	IF(PATIENTBILL.PATIENT_ID IS NULL, 'DIRECT SALES', IF(DATEDIFF(DATE(PATIENTBILL.REVENUE_DATE),DATE(RIC.CREATEDTIME)) = 0, 'NEW', 'REVIEW')) AS VISIT_TYPE,
	IF(PATIENTBILL.PATIENT_ID IS NULL, 0, DATEDIFF(DATE(PATIENTBILL.REVENUE_DATE),DATE(RIC.CREATEDTIME))) AS VISIT_DAYS,

	
	PATIENTBILL.BILL_NO AS BILLNO,
	PATIENTBILL.ID AS EXTERNAL_ID,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%') ,ITEM.ITEMCODE,CHARGE.CHARGECODE) AS ITEMCODE,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%') ,SALDETAIL.ITEMNAME,CHARGE.CHARGE) AS ITEMNAME,
	'' AS MANUFACTURER,
	IF( SERVICE.SERVICE_ID LIKE ('DSAL%'),SALDETAIL.QUANTITY,SERVICE.QUANTITY) AS QUANTITY,
	- IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),(SALDETAIL.QUANTITY*SALDETAIL.MRP) ,SERVICE.SERVICE_AMOUNT) AS TOTAL_AMOUNT,
	- IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),SALDETAIL.DISCOUNTAMOUNT,SERVICE.SERVICE_DISCOUNT) AS DISCOUNT_AMOUNT,	
	- IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),SALDETAIL.REFUNDAMOUNT,(SERVICE.SERVICE_AMOUNT - SERVICE.SERVICE_DISCOUNT)) AS NET_AMOUNT,
	- IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),SALDETAIL.REFUNDAMOUNT,(SERVICE.SERVICE_AMOUNT - SERVICE.SERVICE_DISCOUNT))  AS PATIENT_AMOUNT,
	  0 AS PAYOR_AMOUNT,
	0 AS CGST,
	0 AS SGST,
	0 AS 'GST%',
	0 AS 'Patient_Amount_W/O_GST',
	0 AS 'CGST_Value',
	0 AS 'SGST_Value'
FROM
	BILL_CREDIT_DEBIT_AUDIT AS CREDITDEBIT
	INNER JOIN BILL_PATIENT_BILL AS PATIENTBILL ON PATIENTBILL.ID = CREDITDEBIT.BILL_ID
	INNER JOIN `RT_DATA_ACCOUNT_UNIT` AS ACCUNIT ON ACCUNIT.ID = CREDITDEBIT.`ACCOUNT_UNIT`
	INNER JOIN BILL_SERVICE_DETAIL AS SERVICE ON SERVICE.ID = CREDITDEBIT.BILL_DETAIL_ID
	LEFT JOIN RT_TICKET_DIRECTSALESDETAIL SALDETAIL ON SALDETAIL.SALESID = SERVICE.SERVICE_ID
	AND SALDETAIL.RETURNQUANTITY IS NOT NULL
	LEFT JOIN RT_DATA_CHARGE_DETAIL AS CHARGEDETAIL ON CHARGEDETAIL.ID = SERVICE.CHARGEDETAIL_ID
	INNER JOIN RT_DATA_CORE AS CORE ON CORE.ID = CHARGEDETAIL.ID
	-- JOIN RT_ORGANIZATION_CORE ROC ON ROC.ID=CORE.TENANTID
	INNER JOIN RT_DATA_CHARGE AS CHARGE ON CHARGE.ID = CORE.PARENT_TICKET_ID
	INNER JOIN RT_DATA_ACCOUNT_HEAD AS ACCHEAD ON ACCHEAD.ID = CHARGE.CHARGACCOUNTHEAD
	INNER JOIN `RT_DATA_ACCOUNTSUBHEAD` SUB ON SUB.ID=CHARGE.ACCSUBHEAD
	INNER JOIN `RT_DATA_LEDGER` LED ON LED.ID=CHARGE.CHARGELEDGER
	LEFT JOIN RT_INDIVIDUAL_PATIENT AS PATIENT ON PATIENTBILL.`PATIENT_ID`= PATIENT.ID
	LEFT JOIN RT_INDIVIDUAL_CORE AS RIC ON RIC.ID=PATIENT.ID
	LEFT JOIN RT_DATA_REFERRAL_TYPE RDRT ON RDRT.ID=PATIENT.REFERRALTYPE
	LEFT JOIN RT_DATA_REFERRED_BY RDRB ON RDRB.ID=PATIENT.REFERREDBYCONSULTANT
	LEFT JOIN RT_INDIVIDUAL_CUSTOMER AS CUSTOMER ON CUSTOMER.ID = PATIENTBILL.CUSTOMER_ID
	LEFT JOIN RT_DATA_PAYORTYPE AS PAYORTYPE ON PATIENTBILL.PAYOR_TYPE_ID = PAYORTYPE.ID
	LEFT JOIN RT_DATA_ITEM ITEM ON ITEM.ID = SALDETAIL.ITEMID
	LEFT JOIN RT_DATA_DEPARTMENT DEPT ON DEPT.ID = SALDETAIL.DEPTID
	LEFT JOIN `RT_DATA_ITEM_CATEGORY` CAT ON CAT.ID = ITEM.CATEGORY
WHERE
	(SERVICE.BILL_STATUS != 5 ) AND
	DATE(CREDITDEBIT.CREATED_TIME) BETWEEN curdate() AND curdate()
  	AND (PATIENTBILL.REVENUE_DATE < CREDITDEBIT.CREATED_TIME)
        AND CREDITDEBIT.AMOUNT < 0 -- AND IF(SUBSTRING(PATIENT.`PATIENTID`,1,3) IN('GPP','CTP','MLK','NLP','NMB','VRH') ,ACCUNIT.`ACCOUNTUNIT`, IFNULL(SUBSTRING(PATIENT.`PATIENTID`,1,3),ACCUNIT.`ACCOUNTUNIT`)) = 'CMH'
UNION ALL
SELECT
	-- ROC.DESCRIPTION AS 'entity',
	DATE(SERVICE.MODIFIED_TIME) AS 'TRANSACTION_DATE',
 	ACCUNIT.`ACCOUNTUNIT` AS 'BILLED', 
 	CASE WHEN SUBSTRING(PATIENT.`PATIENTID`,1,3) IN ('GPP','CTP','MLK','NLP','NMB','VRH') THEN ACCUNIT.`ACCOUNTUNIT`
	ELSE
	IFNULL(SUBSTRING(PATIENT.`PATIENTID`,1,3),ACCUNIT.`ACCOUNTUNIT`)
	END AS 'NATIVE',
	IF(PAYORTYPE.PAYORCATEGORY IS NULL, 'Self', IF(PAYORTYPE.PAYORCATEGORY ='Cash','Self',PAYORTYPE.PAYORCATEGORY)) AS PAYORTYPE,
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.CUSTOMERNAME,PATIENT.PATIENTNAME) AS PAYER_NAME,
	IF(PAYORTYPE.PAYORCATEGORY IS NULL, 'SELF PAYING', PAYORTYPE.PAYORTYP) AS AGENCY_NAME,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),IF(CAT.`ITMCGCATEGNAME`='LENS','OPTICALS',SUBSTRING(DEPT.DEPARTMENTNAME,5,LENGTH(DEPT.DEPARTMENTNAME))),ACCHEAD.ACCOUNTHEAD) AS UNIT,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),CAT.`ITMCGCATEGNAME`,SUB.`ACCOUNTSUBHEAD`) AS 'GROUP',
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),ITEM.SUBCATEGORY,LED.`LEDGER`) AS 'SUBGROUP',
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.CUSTOMERNO,PATIENT.PATIENTID) AS MRN,
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.CUSTOMERNAME,PATIENT.PATIENTNAME) AS PATIENT_NAME,
	IF(RDRT.REFERRALTYPENAME IS NULL, '', RDRT.REFERRALTYPENAME) AS REFERRAL_TYPE,
	IF(RDRB.REFERREDBYNAME IS NULL, '', RDRB.REFERREDBYNAME) AS REFERRAL_BY,
	PATIENT.REFERRALTYPEHIDDEN AS REFERRAL_VALUE,
	IF(PATIENTBILL.PATIENT_ID IS NULL,CUSTOMER.AGE,PATIENT.AGE) AS PATIENT_AGE,
		DATE(RIC.CREATEDTIME) AS REGISTERED_DATE,
	IF(PATIENTBILL.PATIENT_ID IS NULL, 'DIRECT SALES', IF(DATEDIFF(DATE(PATIENTBILL.REVENUE_DATE),DATE(RIC.CREATEDTIME)) = 0, 'NEW', 'REVIEW')) AS VISIT_TYPE,
	IF(PATIENTBILL.PATIENT_ID IS NULL, 0, DATEDIFF(DATE(PATIENTBILL.REVENUE_DATE),DATE(RIC.CREATEDTIME))) AS VISIT_DAYS,

	
	PATIENTBILL.BILL_NO AS BILLNO,
	PATIENTBILL.ID AS EXTERNAL_ID,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%') ,ITEM.ITEMCODE,CHARGE.CHARGECODE) AS ITEMCODE,
	IF (SERVICE.SERVICE_ID LIKE ('DSAL%') ,SALDETAIL.ITEMNAME,CHARGE.CHARGE) AS ITEMNAME,
	'' AS MANUFACTURER,
	IF( SERVICE.SERVICE_ID LIKE ('DSAL%'),SALDETAIL.QUANTITY,SERVICE.QUANTITY) AS QUANTITY,
	- IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),(SALDETAIL.QUANTITY*SALDETAIL.MRP) ,SERVICE.SERVICE_AMOUNT) AS TOTAL_AMOUNT,
	- IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),SALDETAIL.DISCOUNTAMOUNT,SERVICE.SERVICE_DISCOUNT) AS DISCOUNT_AMOUNT,	
	- IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),((SALDETAIL.QUANTITY*SALDETAIL.MRP)-IF(SALDETAIL.DISCOUNTAMOUNT IS NULL,0,SALDETAIL.DISCOUNTAMOUNT)) ,(SERVICE.SERVICE_AMOUNT - SERVICE.SERVICE_DISCOUNT)) AS NET_AMOUNT,
	- IF (SERVICE.SERVICE_ID LIKE ('DSAL%'),((SALDETAIL.QUANTITY*SALDETAIL.MRP)-IF(SALDETAIL.DISCOUNTAMOUNT IS NULL,0,SALDETAIL.DISCOUNTAMOUNT)) ,(SERVICE.SERVICE_AMOUNT - SERVICE.SERVICE_DISCOUNT-SERVICE.CLAIM_AMOUNT)) AS PATIENT_AMOUNT,
	  0 AS PAYOR_AMOUNT,
	0 AS CGST,
	0 AS SGST,
	0 AS 'GST%',
	0 AS 'Patient_Amount_W/O_GST',
	0 AS 'CGST_Value',
	0 AS 'SGST_Value'
FROM
	BILL_CREDIT_DEBIT_AUDIT AS CREDITDEBIT
	INNER JOIN BILL_PATIENT_BILL AS PATIENTBILL ON PATIENTBILL.ID = CREDITDEBIT.BILL_ID
	INNER JOIN `RT_DATA_ACCOUNT_UNIT` AS ACCUNIT ON ACCUNIT.ID = CREDITDEBIT.`ACCOUNT_UNIT`
	INNER JOIN BILL_SERVICE_DETAIL AS SERVICE ON SERVICE.ID = CREDITDEBIT.BILL_DETAIL_ID
	LEFT JOIN RT_TICKET_DIRECTSALESDETAIL SALDETAIL ON SALDETAIL.SALESID = SERVICE.SERVICE_ID
	LEFT JOIN RT_DATA_CHARGE_DETAIL AS CHARGEDETAIL ON CHARGEDETAIL.ID = SERVICE.CHARGEDETAIL_ID
	INNER JOIN RT_DATA_CORE AS CORE ON CORE.ID = CHARGEDETAIL.ID
	-- JOIN RT_ORGANIZATION_CORE ROC ON ROC.ID=CORE.TENANTID
	INNER JOIN RT_DATA_CHARGE AS CHARGE ON CHARGE.ID = CORE.PARENT_TICKET_ID
	INNER JOIN RT_DATA_ACCOUNT_HEAD AS ACCHEAD ON ACCHEAD.ID = CHARGE.CHARGACCOUNTHEAD
	INNER JOIN `RT_DATA_ACCOUNTSUBHEAD` SUB ON SUB.ID=CHARGE.ACCSUBHEAD
	INNER JOIN `RT_DATA_LEDGER` LED ON LED.ID=CHARGE.CHARGELEDGER
	LEFT JOIN RT_INDIVIDUAL_PATIENT AS PATIENT ON PATIENTBILL.`PATIENT_ID`= PATIENT.ID
	LEFT JOIN RT_INDIVIDUAL_CORE AS RIC ON RIC.ID=PATIENT.ID
	LEFT JOIN RT_DATA_REFERRAL_TYPE RDRT ON RDRT.ID=PATIENT.REFERRALTYPE
	LEFT JOIN RT_DATA_REFERRED_BY RDRB ON RDRB.ID=PATIENT.REFERREDBYCONSULTANT
	LEFT JOIN RT_INDIVIDUAL_CUSTOMER AS CUSTOMER ON CUSTOMER.ID = PATIENTBILL.CUSTOMER_ID
	LEFT JOIN RT_DATA_PAYORTYPE AS PAYORTYPE ON PATIENTBILL.PAYOR_TYPE_ID = PAYORTYPE.ID
	LEFT JOIN RT_DATA_ITEM ITEM ON ITEM.ID = SALDETAIL.ITEMID
		LEFT JOIN RT_DATA_DEPARTMENT DEPT ON DEPT.ID = SALDETAIL.DEPTID
	LEFT JOIN `RT_DATA_ITEM_CATEGORY` CAT ON CAT.ID = ITEM.CATEGORY
WHERE
	SERVICE.BILL_STATUS = 5 AND PATIENTBILL.BILL_TYPE="IP" AND
	DATE(SERVICE.MODIFIED_TIME) BETWEEN curdate() AND curdate()
	 AND CREDITDEBIT.AMOUNT > 0 -- AND IF(SUBSTRING(PATIENT.`PATIENTID`,1,3) IN('GPP','CTP','MLK','NLP','NMB','VRH') ,ACCUNIT.`ACCOUNTUNIT`, IFNULL(SUBSTRING(PATIENT.`PATIENTID`,1,3),ACCUNIT.`ACCOUNTUNIT`)) = 'CMH'
) AS A
INNER JOIN `RT_ORGANIZATION_CORE` ORGCRE
ON ORGCRE.`ORGANIZATIONNAME`  = A.BILLED
WHERE ORGCRE.STATUS = 1